package org.omg.CORBA;


/**
* org/omg/CORBA/DEMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Saturday, November 3, 2018 at 5:22:36 PM Eastern Daylight Time
*/

public interface DEMS extends DEMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMS
