package org.omg.CORBA;


/**
* org/omg/CORBA/DEMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Saturday, November 3, 2018 at 5:22:36 PM Eastern Daylight Time
*/

public interface DEMSOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, String employeeID, String emailID, org.omg.CORBA.ProjectInfo projectInfo, String location);
  String createERecord (String managerID, String firstName, String lastName, String employeeID, String emailID, String projectID);
  String getRecordCounts (String managerID);
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String printAllData ();
  String printRecord (String managerID, String recordID);
} // interface DEMSOperations
