package org.omg.CORBA;

/**
* org/omg/CORBA/DEMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Tuesday, October 9, 2018 at 4:36:44 PM Eastern Daylight Time
*/

public final class DEMSHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.DEMS value = null;

  public DEMSHolder ()
  {
  }

  public DEMSHolder (org.omg.CORBA.DEMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.DEMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.DEMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.DEMSHelper.type ();
  }

}
