package org.omg.CORBA;

/**
* org/omg/CORBA/ProjectInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Saturday, November 3, 2018 at 5:22:36 PM Eastern Daylight Time
*/

public final class ProjectInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.ProjectInfo value = null;

  public ProjectInfoHolder ()
  {
  }

  public ProjectInfoHolder (org.omg.CORBA.ProjectInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.ProjectInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.ProjectInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.ProjectInfoHelper.type ();
  }

}
