package org.omg.CORBA;


/**
* org/omg/CORBA/ProjectInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Saturday, November 3, 2018 at 5:22:36 PM Eastern Daylight Time
*/

public final class ProjectInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String projectId = null;
  public String clientName = null;
  public String projectName = null;

  public ProjectInfo ()
  {
  } // ctor

  public ProjectInfo (String _projectId, String _clientName, String _projectName)
  {
    projectId = _projectId;
    clientName = _clientName;
    projectName = _projectName;
  } // ctor

public String getProjectId() {
	return projectId;
}

public void setProjectId(String projectId) {
	this.projectId = projectId;
}

public String getClientName() {
	return clientName;
}

public void setClientName(String clientName) {
	this.clientName = clientName;
}

public String getProjectName() {
	return projectName;
}

public void setProjectName(String projectName) {
	this.projectName = projectName;
}

} // class ProjectInfo
