package org.omg.CORBA;


/**
* org/omg/CORBA/DEMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Tuesday, October 9, 2018 at 4:36:44 PM Eastern Daylight Time
*/

public interface DEMS extends DEMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMS
