package org.omg.CORBA;

import java.util.ArrayList;

/**
* org/omg/CORBA/DEMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Tuesday, October 9, 2018 at 4:36:44 PM Eastern Daylight Time
*/

public interface DEMSOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, String employeeID, String emailID, String projectInfo, String location);
  String createERecord (String managerID, String firstName, String lastName, String employeeID, String emailID, String projectID);
  String getRecordCounts (String managerID);
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String printAllData ();
  String printRecord (String managerID, String recordID);
} // interface DEMSOperations
